version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      ruby-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
