# Jekyll configuration

name: Ryan Spletzer
title: Ryan Spletzer
author: Ryan Spletzer
email: ryanspletzer@gmail.com
description: Personal site of Ryan Spletzer

# Url is currently only used only for the RSS feed in feed.xml
url: https://www.spletzer.com
#url: https://ryanspletzer.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

share:
  twitter: true
  facebook: true
  gplus: true
  linkedin: true
  reddit: true
  email: true
  pinterest: false

social:
  github: ryanspletzer
  linkedin: ryanspletzer
  rss: feed.xml

links:
  - text: Mastodon
    url: https://spletzer.com/@ryan
  - text: LinkedIn
    url: https://www.linkedin.com/in/ryanspletzer/
  - text: GitHub
    url: https://github.com/ryanspletzer
  - text: Bluesky
    url: https://bsky.app/profile/ryan.spletzer.com

# Google Analytics key, leave blank to ignore
google_analytics_key: G-92E8FVFHFW
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: www-spletzer-com
comments: true

permalink: /:year/:month/:title/

plugins:
  - jekyll-gist

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

exclude: ["README.md", "LICENSE"]

sass:
    sass_dir: _sass
    style: compressed
