# Jekyll configuration

name: Ryan Spletzer
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
#url: https://ryanspletzer.github.io
url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

share:
  twitter: true
  facebook: true
  gplus: true
  linkedin: true
  reddit: true
  email: true
  pinterest: false

social:
  github: ryanspletzer
  twitter: ryanspletzer
  stackoverflow: ryanspletzer
  linkedin: ryanspletzer
  instagram: ryanspletzer
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ryanspletzer
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
